version: '3.8'

services:
  frontend:
    image: 339712948510.dkr.ecr.eu-north-1.amazonaws.com/tickera/frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=frontend.settings
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - BACKEND_RDS_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      - BACKEND_REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}/${REDIS_DB}
    depends_on:
      - backend_rds
      - backend_redis

  backend_rds:
    image: 339712948510.dkr.ecr.eu-north-1.amazonaws.com/tickera/rds:latest
    container_name: backend_rds
    restart: always
    ports:
      - "5432:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_rds.settings
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  backend_redis:
    image: 339712948510.dkr.ecr.eu-north-1.amazonaws.com/tickera/redis:latets
    container_name: backend_redis
    restart: always
    ports:
      - "6379:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=backend_redis.settings
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
